version: '3'

services:
  web:
    container_name: django-estadodelmce
    build: ./
    command: >
      gunicorn estadodelmce.wsgi:application --bind 0.0.0.0:8000 --workers=4
    env_file:
      - project.env
    expose:
      - 8000
    volumes:
      - staticfiles:/home/app/web/staticfiles  
  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 1337:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - staticfiles:/home/app/web/staticfiles
    depends_on:
      - web

volumes:
  staticfiles:
