version: '3'

services:
  web:
    container_name: django-estadodelmce
    build: ./
    command: >
      gunicorn estadodelmce.wsgi:application --bind 0.0.0.0:8000 --workers=4
    expose:
      - 8000
    volumes:
      - staticfiles:/home/app/web/staticfiles
      - ./estadodelmce/static/:/home/app/web/static
      - ./media:/home/app/web/media
      - ./db.sqlite3:/home/app/web/db.sqlite3
  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - staticfiles:/home/app/web/staticfiles
      - ./media:/home/app/web/media
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - web
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

volumes:
  staticfiles:
  media:
  db.sqlite3:
